---
# Testnet-specific configuration
monad_chain_id: 10143
monad_network_name: "testnet"
monad_snapshot_url: "https://d1v5yevi7k4blc.cloudfront.net"
monad_validators_config_url: "https://bucket.monadinfra.com/validators/testnet/validators.toml"
monad_forkpoint_config_url: "https://bucket.monadinfra.com/forkpoint/testnet/forkpoint.toml"
