---
- name: Start set-hugepages service
  ansible.builtin.systemd:
    name: set-hugepages
    state: started
    enabled: yes
    daemon_reload: yes

- name: Trigger udev rules
  ansible.builtin.command: udevadm trigger

- name: Reload udev rules
  ansible.builtin.command: udevadm control --reload-rules

- name: Reload UFW
  community.general.ufw:
    state: reloaded
