---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Restart execution service
  ansible.builtin.systemd:
    name: "{{ execution_service_identifier }}"
    state: restarted
